import connectDB from './lib/mongodb';
import Job from './models/Job';
import mongoose from 'mongoose';
import dotenv from 'dotenv';

// Load environment variables from .env.local if present
dotenv.config({ path: '.env.local' });

async function seed() {
  try {
    // Establish database connection
    await connectDB();
    console.log('Connected to Database.');

    // Create an array of 10 varying job records
    const jobsData = [
      {
        companyName: "Tech Innovations Inc.",
        website: "https://www.techinnovations.example.com",
        postalAddress: "123 Innovation Drive, Tech City, TX 75001",
        employees: "1000-5000",
        category: "Software/IT",
        designation: "Software Engineer Intern",
        duration: "6 Months",
        placeOfPosting: "Remote / Austin, TX",
        jobDescription: "Exciting opportunity to work on cutting-edge web technologies and cloud infrastructure.",
        cgpa: "7.0 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "Color blindness is acceptable.",
        onboardingInfo: "Virtual onboarding over Zoom in first week of Jan.",
        stipend: "100,000 INR/month",
        stipendDetails: "Includes accommodation allowance and internet reimbursement.",
        primaryContactName: "Jane Doe",
        primaryContactDesignation: "University Recruiter",
        primaryContactEmail: "jane.doe@techinnovations.example.com",
        primaryContactMobile: "+1234567890",
        secondaryContactName: "John Smith",
        secondaryContactDesignation: "HR Manager",
        secondaryContactEmail: "john.smith@techinnovations.example.com",
        secondaryContactMobile: "+1987654321",
        disclosureObjection: "No",
        placementSchedule: {
          "Pre-Placement Talk": { modality: "Virtual", date: "2024-08-15" },
          "Technical Interview": { modality: "Virtual", date: "2024-08-20" }
        },
        consistentHiring: true,
        selectedBtech: ["Computer Science and Engineering", "Information Technology", "Electronics and Communication Engineering"],
        selectedMtech: ["Computer Science and Engineering"],
        hireMscJAM: "No",
        hirePhD: "Yes",
        phdDepartment: "Computer Science",
        hireSkillBased: "Yes",
        skillBasedDetails: "Looking for students with advanced React and Node.js skills.",
        declarantName: "Jane Doe",
        declarationDate: new Date("2024-07-01"),
      },
      {
        companyName: "Global Quant Capital",
        website: "https://gqc.example.com",
        postalAddress: "45 Wall Street, New York, NY 10005",
        employees: "100-500",
        category: "Finance",
        designation: "Quantitative Analyst",
        duration: "Full-Time",
        placeOfPosting: "Mumbai, India",
        jobDescription: "Develop algorithmic trading models using advanced statistical mathematics.",
        cgpa: "8.5 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "No specific medical requirements.",
        onboardingInfo: "In-person onboarding at Mumbai office.",
        stipend: "45,00,000 INR CTC",
        stipendDetails: "Base: 30LPA, Bonus: 15LPA",
        primaryContactName: "Alice Trader",
        primaryContactDesignation: "Talent Acquisition",
        primaryContactEmail: "alice@gqc.example.com",
        primaryContactMobile: "9876543210",
        disclosureObjection: "Yes",
        placementSchedule: {
          "Coding Test": { modality: "Campus Visit", date: "2024-09-01" },
          "Interviews": { modality: "Campus Visit", date: "2024-09-02" }
        },
        consistentHiring: false,
        selectedBtech: ["Computer Science and Engineering", "Mathematics and Computing"],
        selectedDual: ["Mathematics and Computing"],
        hireMscJAM: "Yes",
        selectedMscJAM: ["Mathematics", "Statistics"],
        hirePhD: "No",
        hireSkillBased: "No",
        declarantName: "Alice Trader",
        declarationDate: new Date("2024-07-15"),
      },
      {
        companyName: "Nexus Automotive Corperation",
        website: "https://nexus-auto.example.com",
        postalAddress: "Detroit, Michigan, USA",
        employees: "10000+",
        category: "Core Engineering",
        designation: "Mechanical Design Engineer",
        duration: "Full-Time",
        placeOfPosting: "Pune, India",
        jobDescription: "Design and optimize drivetrain components for EVs.",
        cgpa: "6.5 and above",
        backlog: "YES", // Allows up to 1 backlog
        gender: "All",
        otherMedical: "Vision 6/6 standard requirement.",
        onboardingInfo: "Relocation assistance provided.",
        stipend: "12,00,000 INR CTC",
        stipendDetails: "Flat CTC.",
        primaryContactName: "Robert Ford",
        primaryContactDesignation: "Technical Recruiter",
        primaryContactEmail: "r.ford@nexus-auto.example.com",
        primaryContactMobile: "8887776665",
        disclosureObjection: "No",
        placementSchedule: {
          "Written Test": { modality: "Virtual", date: "2024-09-10" },
          "Technical Round": { modality: "Campus Visit", date: "2024-09-15" }
        },
        consistentHiring: true,
        selectedBtech: ["Mechanical Engineering", "Electrical Engineering"],
        selectedMtech: ["Mechanical Engineering", "Power Electronics"],
        hireMscJAM: "No",
        hirePhD: "Yes",
        phdDepartment: "Mechanical Engineering",
        hireSkillBased: "No",
        declarantName: "Robert Ford",
        declarationDate: new Date("2024-08-01"),
      },
      {
        companyName: "Consulting Partners Group",
        website: "https://cpg.example.com",
        postalAddress: "Boston, MA 02110",
        employees: "5000-10000",
        category: "Consulting",
        designation: "Associate Consultant",
        duration: "Full-Time",
        placeOfPosting: "Gurgaon / Bangalore",
        jobDescription: "Management consulting for Fortune 500 tech clients.",
        cgpa: "7.5 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "N/A",
        onboardingInfo: "1-month training camp in Bangalore.",
        stipend: "20,00,000 INR CTC",
        stipendDetails: "15L fixed, 5L variable.",
        primaryContactName: "Sophia Martinez",
        primaryContactDesignation: "HR Partner",
        primaryContactEmail: "smartinez@cpg.example.com",
        primaryContactMobile: "9998887776",
        secondaryContactName: "Liam Johnson",
        secondaryContactDesignation: "Campus Lead",
        secondaryContactEmail: "ljohnson@cpg.example.com",
        secondaryContactMobile: "9998887775",
        disclosureObjection: "No",
        placementSchedule: {
          "Case Study Round": { modality: "Virtual", date: "2024-10-05" },
          "Partner Round": { modality: "Virtual", date: "2024-10-10" }
        },
        consistentHiring: true,
        selectedBtech: ["Computer Science and Engineering", "Mechanical Engineering", "Civil Engineering", "Chemical Engineering"],
        selectedMba: ["Business Analytics", "General Management"],
        hireMscJAM: "No",
        hirePhD: "No",
        hireSkillBased: "No",
        declarantName: "Sophia Martinez",
        declarationDate: new Date(),
      },
      {
        companyName: "Stratos Aerospace",
        website: "https://stratos.example.com",
        postalAddress: "Toulouse, France",
        employees: "10000+",
        category: "Core Engineering",
        designation: "Aerodynamics Intern",
        duration: "1 Year",
        placeOfPosting: "Bangalore, India",
        jobDescription: "CFD analysis and wind tunnel testing simulations.",
        cgpa: "8.0 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "N/A",
        onboardingInfo: "Laptop and equipment shipped home.",
        stipend: "50,000 INR/month",
        stipendDetails: "Standard internship stipend.",
        primaryContactName: "Marie Curie",
        primaryContactDesignation: "R&D Lead",
        primaryContactEmail: "m.curie@stratos.example.com",
        primaryContactMobile: "7776665554",
        disclosureObjection: "Yes",
        placementSchedule: {
          "Interview": { modality: "Virtual", date: "2024-11-01" }
        },
        consistentHiring: false,
        selectedBtech: ["Mechanical Engineering", "Aerospace Engineering"],
        selectedMtech: ["Aerospace Engineering", "Fluid Dynamics"],
        hireMscJAM: "No",
        hirePhD: "No",
        hireSkillBased: "Yes",
        skillBasedDetails: "ANSYS, OpenFOAM expertise required.",
        declarantName: "Marie Curie",
        declarationDate: new Date("2024-09-10"),
      },
      {
        companyName: "BioGen Informatics",
        website: "https://biogen.example.com",
        postalAddress: "San Francisco, CA",
        employees: "500-1000",
        category: "Biotech/Healthcare",
        designation: "Bioinformatics Data Scientist",
        duration: "Full-Time",
        placeOfPosting: "Remote",
        jobDescription: "Applying machine learning to genomic sequence data.",
        cgpa: "7.0 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "N/A",
        onboardingInfo: "Fully remote onboarding.",
        stipend: "30,00,000 INR CTC",
        stipendDetails: "Includes equity stock options.",
        primaryContactName: "Dr. Alan Turing",
        primaryContactDesignation: "Chief Scientist",
        primaryContactEmail: "aturing@biogen.example.com",
        primaryContactMobile: "8885551234",
        disclosureObjection: "No",
        placementSchedule: {
          "Take-Home Assignment": { modality: "Virtual", date: "2024-09-20" },
          "Technical Panel": { modality: "Virtual", date: "2024-09-27" }
        },
        consistentHiring: true,
        selectedBtech: ["Computer Science and Engineering", "Biotechnology"],
        selectedMtech: ["Computer Science and Engineering", "Biotechnology"],
        selectedDual: ["Biotechnology", "Computer Science"],
        hireMscJAM: "No",
        hirePhD: "Yes",
        phdDepartment: "Biosciences and Bioengineering",
        hireSkillBased: "No",
        declarantName: "Dr. Alan Turing",
        declarationDate: new Date("2024-08-20"),
      },
      {
        companyName: "SecureNet Cybersecurity",
        website: "https://securenet.example.com",
        postalAddress: "Tel Aviv, Israel",
        employees: "100-500",
        category: "Software/IT",
        designation: "Security Researcher",
        duration: "Full-Time",
        placeOfPosting: "Hyderabad, India",
        jobDescription: "Vulnerability research, penetration testing, and writing exploits.",
        cgpa: "6.0 and above", // Emphasis on skills over CGPA
        backlog: "YES",  // Flexible with backlogs
        gender: "All",
        otherMedical: "N/A",
        onboardingInfo: "Background verification takes 3 weeks.",
        stipend: "25,00,000 INR CTC",
        stipendDetails: "Flat salary. No variable.",
        primaryContactName: "David Cohen",
        primaryContactDesignation: "SecOps Manager",
        primaryContactEmail: "d.cohen@securenet.example.com",
        primaryContactMobile: "9990001112",
        disclosureObjection: "Yes",
        placementSchedule: {
          "CTF Challenge": { modality: "Virtual", date: "2024-10-15" },
          "Interview": { modality: "Campus Visit", date: "2024-10-25" }
        },
        consistentHiring: false,
        selectedBtech: ["Computer Science and Engineering"],
        selectedIntMtech: ["Mathematics and Computing", "Computer Science"],
        hireMscJAM: "No",
        hirePhD: "No",
        hireSkillBased: "Yes",
        skillBasedDetails: "Must have OSCP, OSEP, or high rank on HackTheBox/Bugcrowd.",
        declarantName: "David Cohen",
        declarationDate: new Date("2024-09-01"),
      },
      {
        companyName: "Green Earth Renewables",
        website: "https://greenearth.example.com",
        postalAddress: "Oslo, Norway",
        employees: "1000-5000",
        category: "Energy",
        designation: "Process Engineer Intern",
        duration: "6 Months",
        placeOfPosting: "Chennai, India",
        jobDescription: "Optimizing green hydrogen extraction processes.",
        cgpa: "7.5 and above",
        backlog: "NO",
        gender: "Female", // Diversity hiring drive
        otherMedical: "Clearance required for plant visits.",
        onboardingInfo: "Plant safety training on day 1.",
        stipend: "60,000 INR/month",
        stipendDetails: "Travel and accommodation provided for plant visits.",
        primaryContactName: "Ingrid Nilsen",
        primaryContactDesignation: "HR Lead - Asia",
        primaryContactEmail: "inilsen@greenearth.example.com",
        primaryContactMobile: "6665554443",
        disclosureObjection: "No",
        placementSchedule: {
          "Aptitude Test": { modality: "Virtual", date: "2024-11-10" },
          "Technical Interview": { modality: "Virtual", date: "2024-11-15" }
        },
        consistentHiring: true,
        selectedBtech: ["Chemical Engineering", "Electrical Engineering"],
        selectedMtech: ["Chemical Engineering", "Energy Systems"],
        hireMscJAM: "Yes",
        selectedMscJAM: ["Chemistry", "Physics"],
        hirePhD: "No",
        hireSkillBased: "No",
        declarantName: "Ingrid Nilsen",
        declarationDate: new Date("2024-10-01"),
      },
      {
        companyName: "UrbanArch Design House",
        website: "https://urbanarch.example.com",
        postalAddress: "London, UK",
        employees: "50-100",
        category: "Architecture/Design",
        designation: "Junior Architect",
        duration: "Full-Time",
        placeOfPosting: "New Delhi, India",
        jobDescription: "Drafting, 3D modeling, and sustainable building design.",
        cgpa: "7.0 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "N/A",
        onboardingInfo: "Portfolio review mandatory during onboarding.",
        stipend: "10,00,000 INR CTC",
        stipendDetails: "Yearly performance bonuses.",
        primaryContactName: "Sir Norman Foster (Pseudo)",
        primaryContactDesignation: "Principal Architect",
        primaryContactEmail: "nfoster@urbanarch.example.com",
        primaryContactMobile: "9871236540",
        disclosureObjection: "No",
        placementSchedule: {
          "Portfolio Review": { modality: "Virtual", date: "2024-12-01" },
          "Design Charette": { modality: "Campus Visit", date: "2024-12-05" }
        },
        consistentHiring: false,
        selectedBtech: ["Civil Engineering", "Architecture"], // Assuming Architecture exists or aligns
        selectedMtech: ["Structural Engineering"],
        hireMscJAM: "No",
        hirePhD: "No",
        hireSkillBased: "Yes",
        skillBasedDetails: "AutoCAD, Revit, SketchUp, Lumion.",
        declarantName: "John Architect",
        declarationDate: new Date("2024-11-01"),
      },
      {
        companyName: "EduTech Pioneers",
        website: "https://edutechpioneers.example.com",
        postalAddress: "Bangalore, India",
        employees: "5000-10000",
        category: "Education/E-Learning",
        designation: "Product Manager",
        duration: "Full-Time",
        placeOfPosting: "Bangalore, India",
        jobDescription: "Drive product lifecycle and user growth for our core learning app.",
        cgpa: "6.5 and above",
        backlog: "NO",
        gender: "All",
        otherMedical: "N/A",
        onboardingInfo: "1 week bootcamp in Bangalore HQ.",
        stipend: "18,00,000 INR CTC",
        stipendDetails: "14L Fixed, 4L ESM.",
        primaryContactName: "Rahul Sharma",
        primaryContactDesignation: "VP Product",
        primaryContactEmail: "rahul.s@edutechpioneers.example.com",
        primaryContactMobile: "7778889990",
        secondaryContactName: "Neha Gupta",
        secondaryContactDesignation: "HR Associate",
        secondaryContactEmail: "neha.g@edutechpioneers.example.com",
        secondaryContactMobile: "7778889991",
        disclosureObjection: "No",
        placementSchedule: {
          "Group Discussion": { modality: "Campus Visit", date: "2024-11-20" },
          "Product Sense Interview": { modality: "Campus Visit", date: "2024-11-21" }
        },
        consistentHiring: true,
        selectedBtech: ["Computer Science and Engineering", "Information Technology", "Electronics and Communication Engineering", "Mechanical Engineering"],
        selectedMba: ["General Management", "Marketing", "Finance"],
        selectedMscTech: ["Information Systems"],
        hireMscJAM: "No",
        hirePhD: "No",
        hireSkillBased: "No",
        declarantName: "Rahul Sharma",
        declarationDate: new Date("2024-10-15"),
      }
    ];

    // Save all to database
    const savedJobs = await Job.insertMany(jobsData);
    console.log(`Successfully added ${savedJobs.length} example Job records.`);

  } catch (error) {
    console.error('Error seeding data:', error);
  } finally {
    // Disconnect and exit
    await mongoose.disconnect();
    console.log('Database connection closed.');
    process.exit(0);
  }
}

seed();
